import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Harsha Kotla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
      </Head>
      <main>
        <div class="container" style={{maxWidth: 1100}}><br/>
        <a className="btn btn-light" href="https://github.com/harsha-kotla" target="_blank" style={{float: "right"}}>Github</a>

          <h3>Harsha Kotla</h3>

          <br/>
          <h5>About me:</h5>

          <p>
            Hi, I'm Harsha Kotla. I love programming. I mostly work on web development, but I also love algorithms in C++ and Java. 
          </p>
          <p>Some facts about me:</p>
          <ul>
            <li>I love programming as I just told you</li>
            <li>I love solving math problems</li>
            <li>I love playing tennis</li>
          </ul>
          
          <h5>Courses:</h5>
          <ul>
            <li>Udemy MERN stack</li>
            <li>Udemy Intro to Machine Learning</li>
            <li>Coursera HTML CSS and JS course</li>
          </ul>
        </div>
      </main>
    </>
  )
}
